export default {
   image: {
      t01: true,
      t02: true,
      t03: true,
      t04: true,
      t05: true,
      t06: false,
      t07: false,
      t08: false,
      t09: false,
      t10: false,
      t11: false,
      t12: false,
      controller: {
         delete: true,
         thumbs: true,
         rotate: true,
      },
   },
   text: {
      t01: false,
      t02: false,
      t03: true,
      t04: true,
      t05: true,
      t06: true,
      t07: true,
      t08: true,
      t09: true,
      t10: true,
      t11: true,
      t12: true,
      controller: {
         delete: true,
         thumbs: true,
         rotate: true,
      },
   },
   audio: {
      t01: false,
      t02: false,
      t03: true,
      t04: true,
      t05: false,
      t06: false,
      t07: false,
      t08: false,
      t09: false,
      t10: false,
      t11: false,
      t12: false,
      controller: {
         delete: true,
         thumbs: false,
         rotate: false,
      },
   },
   video: {
      t01: false,
      t02: false,
      t03: true,
      t04: true,
      t05: true,
      t06: false,
      t07: false,
      t08: false,
      t09: false,
      t10: false,
      t11: false,
      t12: false,
      controller: {
         delete: true,
         thumbs: true,
         rotate: false,
      },
   },
}
